#!/usr/bin/env bash
echo "remove spaces, commas and stuff that should not be in file names"

echo "1: rename directories"
find -name "* *" -type d | rename 's/ /_/g'    # do the directories first


echo "2: rename files"

echo "2.1: remove spaces"
find -name "* *" -type f | rename 's/ /_/g'
echo "2.2: remove commas"
find -name "*,*" -type f | rename 's/\,//g'
echo "2.3: remove minus signs"
find -name "*-*" -type f | rename 's/-//g'
echo "2.4: do nothing about dots because I don't know yet how to deal with them"


echo "3: merge delimiters"
find -name "*_*" -type f | rename 's/____/_/g'
find -name "*_*" -type f | rename 's/___/_/g'
find -name "*_*" -type f | rename 's/__/_/g'


